name: CI - Build

on:
  pull_request:
    branches: [main, develop] # これらのブランチへの PR で実行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install native build dependencies (for better-sqlite3)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          CI: 'true'
        run: npm run build
